services:
  # Backend API Service
  - type: web
    name: datadashpro-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.12
      - key: PORT
        value: 8000

  # Frontend Static Site
  - type: static
    name: datadashpro-frontend
    rootDir: frontend
    buildCommand: echo "No build required"
    staticPublishPath: .
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
